# ─── Render Blueprint for monorepo ────────────────────────────────────

services:
  # ─── Backend Nest.js ────────────────────────────────────────────────
  - name: paggo-backend
    type: web
    plan: free
    region: oregon
    branch: main
    runtime: node

    # build & start inside `backend/`
    buildCommand: |
      cd backend
      npm install --legacy-peer-deps
      npm run build
    startCommand: |
      cd backend
      npm run start:prod

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: paggo-db
          property: connectionString
      - key: JWT_SECRET
        value: "${JWT_SECRET}"
      - key: OCR_SPACE_KEY
        value: "${OCR_SPACE_KEY}"
      - key: OPENAI_API_KEY
        value: "${OPENAI_API_KEY}"

  # ─── Frontend Next.js ────────────────────────────────────────────────
  - name: paggo-frontend
    type: web
    plan: free
    region: oregon
    branch: main
    runtime: node

    # build & start inside `frontend/`
    buildCommand: |
      cd frontend
      npm install --legacy-peer-deps
      npm run build
    startCommand: |
      cd frontend
      npm run start

    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "https://paggo-backend-700c.onrender.com/api"


# ─── Managed Postgres Database ────────────────────────────────────────
databases:
  - name: paggo-db
    region: oregon
    plan: free
